## ✏️ 前言  
* 🧮 数据处理主要使用**pandas==1.5.3**  
* 🔭 可视化部分主要使用**matplotlib==3.7.2**  
* 🔍 部分代码过长 已进行隐藏处理 可右上角👉**Fork**👉 运行查看  

## 📑 个人信息  
* **社区个人专栏**： **[西瓜的数据研究院](https://www.heywhale.com/home/column/623c61fc74f0cb0017cce37a)**  
* **个人微信公众号**：<u>关注我，第一时间接收新鲜的数据分析实战项目！</u>  
![Image Name](https://cdn.kesci.com/upload/sd7j4ci93u.png?imageView2/0/w/960/h/960)  

## 🔆 推荐项目  
* [【每周挑战】水质安全分析及建模预测](https://www.heywhale.com/mw/project/6576c764c5a8cddbda981a9b)  
* [【实战案例】送餐耗时因素分析及预测](https://www.heywhale.com/mw/project/64c767043cbcbda8f57a2bf7)  
* [【可视化】2023年中国大学评级可视化分析](https://www.heywhale.com/mw/project/6493caf3a97968605244a4aa)  
* [【异常值检测】 基于KMeans的异常值检测实战](https://www.heywhale.com/mw/project/647d8f1ee3ed2557756babf5)  
* [【回归】使用机器学习算法对钻石价格进行预测](https://www.heywhale.com/mw/project/63392e3125e45a9476edc47e)  
* [【深度学习】电商评论文本情感分类](https://www.heywhale.com/mw/project/632550e2044ae11cfb0f4c83)  
* [【LightGBM】LightGBM+贝叶斯优化预测银行卡电信诈骗](https://www.heywhale.com/mw/project/62eba9e9dd8cd3138e76b6a9)  
* [【LightGBM】使用LightGBM算法对短文本进行幽默性检测](https://www.heywhale.com/mw/project/625e63b826bb0900178b09a7)  
* [【XGBoost】使用XGBoost算法对信用卡交易进行诈骗预测](https://www.heywhale.com/mw/project/62bd3d81913a54a66019c1f8)  
* [【Catboost】使用Catboost算法对航班延误进行分类预测](https://www.heywhale.com/mw/project/62c6936557d4f260d553a5a7)  
* [【分类】使用机器学习算法对印度肝病患者进行分类预测](https://www.heywhale.com/mw/project/62b2cc3982643be71027a966)  
* [【可视化】关于医保数据的可视化分析]()  
* [【奥运】2022北京冬奥会奖牌榜可视化分析](https://www.heywhale.com/mw/project/62124fbe68364e0017a48a23)  
* [【高考】中国高考数据，往后的录取率会是多少？](https://www.heywhale.com/mw/project/61b73a033c18f70018c04710)  
* [【唐山打人事件】一图了解唐山烧烤店内女子遭围殴事件脉络](https://www.heywhale.com/mw/project/62a587769e688fdaa3dbdd78)  
* [【新冠疫情】全球新冠疫情现状可视化](https://www.heywhale.com/mw/project/62d1670fcadd4eff9e2de601)  
* [【空难】了解空难历史，关于历史空难数据的探索](https://www.heywhale.com/mw/project/6276203ad0bd1f00173f48f5)  
* [【爬虫】使用selenium爬取房天下广州二手房房源数据](https://www.heywhale.com/mw/project/6303b3bef31025b77778b948)  

***🔭🔭 更多项目作品可移步关注西瓜的个人专栏 [西瓜的数据研究院](https://www.heywhale.com/home/column/623c61fc74f0cb0017cce37a)***  

## ❗温馨提示  
部分代码过长，本文已进行隐藏处理，可点击右上方**在线编辑**运行项目查看隐藏代码

## 1. 导入第三方包

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

## 加载字体
font_path = "ZhuqueFangsong-Regular.ttf"
font_manager.fontManager.addfont(font_path)
prop = font_manager.FontProperties(fname=font_path)

## 定义全局使用
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = prop.get_name()
plt.rcParams['axes.unicode_minus'] = False

## 2. 数据读取及预览

In [18]:
df = pd.read_csv("/home/mw/input/marrieddata8411/data.csv")
df.head()

,地区,年份,结婚登记(万对),内地居民登记结婚(万对),内地居民初婚登记(万对),内地居民再婚登记(万对),涉外及港澳台居民登记结婚(万对),离婚登记(万对),粗离婚率(‰)
0,北京市,2022年,9.13,9.09,11.81,6.45,0.04,4.42,2.02
1,北京市,2021年,10.34,10.29,13.63,7.04,0.04,5.04,2.30
2,北京市,2020年,11.38,11.34,12.43,10.33,0.04,8.19,3.77
3,北京市,2019年,12.90,12.82,14.15,11.64,0.08,8.38,3.89
4,北京市,2018年,13.78,13.70,16.92,10.65,0.08,7.41,3.43

## 3. 数据预处理

In [19]:
items = [
    [
        col, 
        df[col].dtype, 
        df[col].isnull().sum(),
    ] for col in df
]

display(pd.DataFrame(data=items, columns=[
    'Attributes',
    'Data Type',
    'Total Missing',
]))

         Attributes Data Type  Total Missing
0                地区    object              0
1                年份    object              0
2          结婚登记(万对)   float64              0
3      内地居民登记结婚(万对)   float64              0
4      内地居民初婚登记(万对)   float64              0
5      内地居民再婚登记(万对)   float64              1
6  涉外及港澳台居民登记结婚(万对)   float64             50
7          离婚登记(万对)   float64              0
8           粗离婚率(‰)   float64            217

In [20]:
# 缺失值处理
df["tmp"] = df["结婚登记(万对)"] - df["内地居民登记结婚(万对)"]
df["涉外及港澳台居民登记结婚(万对)"].fillna(df["tmp"], inplace=True)
df.drop("tmp", axis=1, inplace=True)

# 重复着处理
df.drop_duplicates(inplace = True)

In [21]:
def clean_cityname(city_name):
    if city_name.endswith("市") or city_name.endswith("省"):
        res = city_name[:-1]
    elif city_name != "内蒙古自治区":
        res = city_name[:2]
    else:
        res = city_name[:3]
    return res

df["地区"] = df["地区"].map(lambda x:clean_cityname(x))

## 4. 数据可视化

In [22]:
# 近10年结婚/离婚人数
data = df.query("年份 > '2013'")

tmp = data.groupby("年份").agg({"结婚登记(万对)":"sum","离婚登记(万对)":"sum"})

In [23]:
fig = plt.figure(figsize=(12,6),dpi=100)
ax = fig.add_subplot(111)

total_width, n = 0.7, 2
width = total_width / n

x = np.arange(len(tmp.index))
x = x - (total_width - width) / 2

bar1 = plt.bar(x - width/2, tmp["结婚登记(万对)"], width=width, label="结婚登记(万对)", fc="#5698c3")
bar2 = plt.bar(x + width/2, tmp["离婚登记(万对)"], width=width, label="离婚登记(万对)", fc="#68b88e")

def annotate(ax, x, y, text, fc="#ff7777", y0=0):
    y = y - 0.5
    ax.annotate(
        " " + text + " ",
        xy=(x, y),
        xycoords="data",
        xytext=(0, 28),
        textcoords="offset points",
        color="white",
        size=12,
        va="center",
        ha="center",
        weight="bold",
        bbox=dict(boxstyle="round", fc=fc, ec="none"),
        arrowprops=dict(
            arrowstyle="fancy, tail_width=1.2", 
            fc=fc, ec="none", patchA=None
        ), 
    )
    plt.plot([x, x], [y, y0], color="black", 
             linestyle="-", linewidth=1, alpha=0.25)
annotate(ax, 7.45, 1000, "2021年起，离婚“冷静期”开始执行", fc="#68b88e")

for spine in ax.spines.values():  
    spine.set_visible(False)  
ax.spines['bottom'].set_visible(True)

for a,b in zip(x-width,tmp["结婚登记(万对)"]):
    plt.text(a+.01,b+10,b,color="#5698c3")
for a,b in zip(x,tmp["离婚登记(万对)"]):
    plt.text(a+.01,b+10,b,color="#68b88e")
plt.xticks(x,tmp.index,fontsize=13,alpha=0.7)
plt.yticks([])
plt.legend(ncol=2,loc="upper center",frameon=False,fontsize=12)
plt.title("近10年(2013-2022)我国结婚离婚登记情况",fontsize=20)

plt.show()

* 近10年，全国结婚登记总数呈下降趋势，并在2019年开始跌至1000万对以下。  
* 在2019年及之前，我国每年离婚登记数量呈上升趋势，但在2019年之后呈下降趋势，尤其是在2021年起执行离婚“冷静期”，离婚登记数得到进一步下降。

In [24]:
tmp = data.groupby("年份").agg({"粗离婚率(‰)":"mean"}).round(2)

In [25]:
fig = plt.figure(figsize=(12,6),dpi=100)
ax = fig.add_subplot(111)

#plt.step(tmp.index, tmp["粗离婚率(‰)"], where='post')  
plt.plot(tmp.index, tmp["粗离婚率(‰)"],linewidth=3,label='粗离婚率(‰)',color='#2c9678',zorder=0)  
def annotate(ax, x, y, text, fc="#ff7777", y0=0):
    y = y - 0.1
    ax.annotate(
        " " + text + " ",
        xy=(x, y),
        xycoords="data",
        xytext=(0, 28),
        textcoords="offset points",
        color="white",
        size=12,
        va="center",
        ha="center",
        weight="bold",
        bbox=dict(boxstyle="round", fc=fc, ec="none"),
    )
plt.scatter(tmp["粗离婚率(‰)"].idxmax(), tmp["粗离婚率(‰)"].max(),zorder=1,s=tmp["粗离婚率(‰)"].max()*30)
annotate(ax, tmp["粗离婚率(‰)"].idxmax(), tmp["粗离婚率(‰)"].max(), str(tmp["粗离婚率(‰)"].max()) + "\n近年最高点", fc="#68b88e")
plt.scatter(tmp["粗离婚率(‰)"].idxmin(), tmp["粗离婚率(‰)"].min(),zorder=1,s=tmp["粗离婚率(‰)"].min()*30)
annotate(ax, tmp["粗离婚率(‰)"].idxmin(), tmp["粗离婚率(‰)"].min(), str(tmp["粗离婚率(‰)"].min()) + "\n近年最低点", fc="#68b88e")

for spine in ax.spines.values():  
    spine.set_visible(False)  
ax.spines['bottom'].set_visible(True)

plt.ylim(0,5)
plt.grid(axis='y',linestyle='--')
plt.xticks(tmp.index,fontsize=12,alpha=0.7)
plt.yticks(np.arange(0,5.5,1),fontsize=10,alpha=0.7)
plt.legend(loc="upper center",frameon=False,fontsize=12)
plt.title("近10年(2013-2022)我国粗离婚率变化趋势",fontsize=20)

# 显示图形  
plt.show()

* 近10年间，我国此离婚率整体处于2‰ ~ 4‰，并在2021年执行离婚“冷静期”起，粗离婚率进一步下降。  
* 2019年是近年的粗离婚率最高值，达到3.37‰，而粗离婚率最低值出现在2022年，低至2.08‰.

In [26]:
tmp = data.groupby("年份").agg({"内地居民初婚登记(万对)":"sum","内地居民再婚登记(万对)":"sum"})

In [27]:
fig = plt.figure(figsize=(12,6),dpi=100)
ax = fig.add_subplot(111)

bar1 = plt.bar(tmp.index, tmp["内地居民再婚登记(万对)"], width=0.4, fc="#68b88e", label="再婚登记(万对)")
bar2 = plt.bar(tmp.index, tmp["内地居民初婚登记(万对)"], bottom=tmp["内地居民再婚登记(万对)"]+95, width=0.4,fc="#5698c3",label="初婚登记(万对)")

plt.bar_label(bar1, color="#68b88e")
plt.bar_label(bar2, color="#5698c3")

for spine in ax.spines.values():  
    spine.set_visible(False)  
ax.spines['bottom'].set_visible(True)

plt.xticks(tmp.index,fontsize=12,alpha=0.7)
plt.ylim(0,3000)
plt.yticks([])
plt.legend(loc="upper center",ncol=2,frameon=False,fontsize=12)
plt.title("近10年(2013-2022)我国内地居民结婚对数变化",fontsize=20)

plt.show()

* 近10年间，我国的初婚登记数量逐年下降，而再婚登记数量波动不大，整体处于300万 ~ 500万对之间

In [28]:
df2022 = data.query("年份 == '2022年'")

df2022["初婚占比(%)"] = df2022["内地居民初婚登记(万对)"].map(lambda x:round(x/df2022["内地居民初婚登记(万对)"].sum(),4)*100)
df2022["再婚占比(%)"] = df2022["内地居民再婚登记(万对)"].map(lambda x:round(x/df2022["内地居民再婚登记(万对)"].sum(),4)*100)

In [29]:
fig = plt.figure(figsize=(12,10),dpi=100)
ax = fig.add_subplot(111)

bar1 = plt.barh(df2022["地区"], df2022["初婚占比(%)"]*-1, fc="#68b88e", label="初婚占比")
bar2 = plt.barh(df2022["地区"], df2022["再婚占比(%)"]*+1, fc="#5698c3", label="再婚占比")

for spine in ax.spines.values():  
    spine.set_visible(False) 

plt.bar_label(bar1, df2022["初婚占比(%)"].map(lambda x:str(round(x,2))+"%"), padding=2.5, color="#68b88e")
plt.bar_label(bar2, df2022["再婚占比(%)"].map(lambda x:str(round(x,2))+"%"), padding=2.5, color="#5698c3")

plt.xticks([])
plt.yticks(df2022["地区"],fontsize=12,alpha=0.6)
plt.gca().axes.get_yaxis().set_tick_params(which='both', size=0)
plt.legend(loc=(.75,1), ncol=2, frameon=False,fontsize=10)
plt.title("2022年我国各地区结婚对数占比",fontsize=20)

plt.show()

* 2022年中，初婚登记占比最高的地区是广东，占比达到9.21%，其次是河南以及江苏；而占比最低的地区是西藏，初婚登记占比仅有0.44%  
* 再婚占比中，四川地区的占比最高，达到8.08%，其次是山东及河南，占比最低的是西藏，占比仅有0.11%

In [30]:
area_dict = {
    "东北地区":["辽宁","吉林","黑龙江"],
    "东部地区":["北京","天津","河北","上海","江苏","浙江","福建","山东","广东","海南"],
    "中部地区":["山西","安徽","江西","河南","湖北","湖南"],
    "西部地区":["内蒙古","广西","重庆","四川","贵州","云南","西藏","陕西","甘肃","青海","宁夏","新疆"]
    }

def get_area(cityname):
    for key,value in area_dict.items():
        if cityname in value:
            return key

df2022["地区划分"] = df2022["地区"].map(lambda x:get_area(x))

In [31]:
df2022["结婚登记占比(%)"] = df2022["结婚登记(万对)"].map(lambda x:round(x/df2022["结婚登记(万对)"].sum(),4)*100)
df2022["离婚登记占比(%)"] = df2022["离婚登记(万对)"].map(lambda x:round(x/df2022["离婚登记(万对)"].sum(),4)*100)

x_g, y_g = round(df2022["结婚登记占比(%)"].mean(),2), round(df2022["粗离婚率(‰)"].mean(),2)

In [32]:
area_colors = ["#de1c31","#346c9c","#41ae3c","#fecc11"]
sns.set_palette(area_colors)

x = df2022["结婚登记占比(%)"].tolist()
y = df2022["粗离婚率(‰)"].tolist()
cityname = df2022["地区"].tolist()

fig = plt.figure(figsize=(8,8),dpi=100)
ax = fig.add_subplot(111)

sns.scatterplot(x, y, s=70, hue=df2022["地区划分"], zorder=2)
sns.scatterplot([x_g], [y_g], color="#000", alpha=.5, s=200, zorder=2)

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.spines["left"].set_visible(False)
ax.spines["bottom"].set_visible(False)

for i in range(len(x)):
    if cityname[i] != "吉林" and cityname[i] != "湖南" and cityname[i] != "陕西":
        plt.annotate(cityname[i], (x[i]-.20, y[i]+.04), alpha=.7) 
    else:
        plt.annotate(cityname[i], (x[i]-.55, y[i]-.02), alpha=.7) 

plt.annotate("全国平均", (x_g-.6, y_g+.05), alpha=.7, fontsize=12) 

plt.xticks(fontsize=12, alpha=.7)
plt.xlabel("结婚登记占比(%)", fontsize=16, alpha=.7)
plt.yticks(fontsize=12, alpha=.7)
plt.ylabel("粗离婚率(‰)", rotation=0, labelpad=55, fontsize=16, alpha=.7)
plt.grid(zorder=1,alpha=.35)
plt.gca().axvline(x=0, color='w')
plt.legend(frameon=False,fontsize=12)
plt.title("2022年我国各地区结婚登记对数占比及粗离婚率详情",fontsize=18,pad=20)

plt.show()

* 2022年中，结婚登记占比较高的三个地区分别是广东、河南以及四川，三者中粗离婚率较高的是四川。  
* 上海、四川以及海南的粗离婚率较低，且三者的结婚登记占比也是较低的。

项目使用数据👉[近20年(2003-2022年)我国各地区结婚离婚数据](https://www.heywhale.com/mw/dataset/657bf6b02c9ef87f4348ee06)  

欢迎各位**Fork**、**点赞**